// PokerTraining — Texas Hold'em simulator
// Copyright (c) 2025 Marc Ennaji
// Licensed under the MIT License — see LICENSE file for details.

#pragma once

#define MIN_NUMBER_OF_PLAYERS 2
#define MAX_NUMBER_OF_PLAYERS 10

#define DEBUG_MODE 0
#define SQLITE_LOG 1
#define SQLITE_LOG_ALL 0

#define POKERTRAINING_VERSION_MAJOR 0
#define POKERTRAINING_VERSION_MINOR 1
#define POKERTRAINING_VERSION ((POKERTRAINING_VERSION_MAJOR << 8) | POKERTRAINING_VERSION_MINOR)

#define POKERTRAINING_BETA_REVISION 0
#define POKERTRAINING_BETA_RELEASE_STRING "1.5.0"

#define SQLITE_LOG_VERSION 1

#define MIN_HANDS_STATISTICS_ACCURATE 30
