name: Run GoogleTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"   # Nightly at 2 AM UTC

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang g++-10 qt6-base-dev qt6-tools-dev qt6-tools-dev-tools

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ -DUSE_QML=OFF

      - name: Build
        run: cmake --build build --target unit_tests

      - name: Run unit tests
        run: ./build/tests/unit_tests

  e2e-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang g++-10 qt6-base-dev qt6-tools-dev qt6-tools-dev-tools

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ -DUSE_QML=OFF

      - name: Build
        run: cmake --build build --target e2e_tests

      - name: Run E2E tests
        run: ./build/tests/e2e_tests
