name: Run GoogleTest Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang g++-10 qt6-base-dev qt6-tools-dev qt6-tools-dev-tools

      # Step 3: Configure the build
      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++

      # Step 4: Build the project
      - name: Build
        run: cmake --build build

      # Step 5: Debug - List directory structure
      - name: List build directory
        run: ls -R build

      # Step 6: Run the tests
      - name: Run tests
        run: ./build/tests/core_tests